name: conda-store-server-dev
channels:
  - conda-forge
dependencies:
  # conda builds
  - conda
  - conda-docker
  - conda-pack
  # web server
  - celery
  - flower
  - redis-py
  - sqlalchemy
  - psycopg2
  - pymysql
  - requests
  - uvicorn
  - fastapi
  - pydantic
  - pyyaml
  - traitlets
  - yarl
  - pyjwt
  - filelock
  # artifact storage
  - minio
  # CLI
  - typer

  # dev dependencies
  - pytest
  - pytest-mock
  - black ==21.5b0
  - flake8
  - sphinx
  - recommonmark
  - pydata-sphinx-theme
