version: "3.8"

volumes:
  conda_store_data:

services:
  conda-store-worker:
    build: ../../conda-store-server
    volumes:
      - conda_store_data:/opt/conda-store/
      - ./assets/conda_store_config.py:/etc/conda-store/conda_store_config.py:ro
    depends_on:
      conda-store-server:
        condition: service_healthy
    platform: linux/amd64
    command: ['conda-store-worker', '--config', '/etc/conda-store/conda_store_config.py']

  conda-store-server:
    build: ../../conda-store-server
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    volumes:
      - ./assets/conda_store_config.py:/etc/conda-store/conda_store_config.py:ro
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:5000/api/v1/"]
      interval: 10s
      timeout: 5s
      retries: 5
    platform: linux/amd64
    command: ['conda-store-server', '--config', '/etc/conda-store/conda_store_config.py']
    ports:
      - "5000:5000"

  jupyterhub:
    build: ../../conda-store
    user: "1000:1000"
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:8000/hub/api/"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - conda_store_data:/opt/conda-store
      - ./assets/jupyter_notebook_config.py:/etc/jupyter/jupyter_notebook_config.py:ro
      - ./assets/jupyterhub_config.py:/opt/jupyterhub/jupyterhub_config.py:ro
    platform: linux/amd64
    command: ['/opt/conda/envs/conda-store/bin/jupyterhub', '--config', '/opt/jupyterhub/jupyterhub_config.py']
    ports:
      - "8000:8000"

  minio:
    image: minio/minio:RELEASE.2020-11-10T21-02-24Z
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 10s
      timeout: 5s
      retries: 5
    entrypoint: sh
    command: -c 'mkdir -p /data/conda-store && /usr/bin/minio server /data'
    environment:
      MINIO_ACCESS_KEY: admin
      MINIO_SECRET_KEY: password

  postgres:
    image: postgres:13
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: conda-store

  mysql:
    image: mysql:8.0
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      MYSQL_ROOT_PASSWORD: hbgY8bkoWPMM7EjtcD6wrlVX
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: conda-store
